exclude: '.git|venv|__pycache__|htmlcov|img'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--src-path", "forge_api"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--ignore=W0611,W503,W504,F401,E203"]
